USE Lab3_DBMS
GO

INSERT INTO Library VALUES(20, 'Timisoara', 100)
ALTER DATABASE Lab3_DBMS SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE Library SET Address = 'New Name 1' WHERE ID = 20
WAITFOR DELAY '00:00:05'
COMMIT TRAN

-- ALTER DATABASE Lab3_DBMS SET ALLOW_SNAPSHOT_ISOLATION OFF
-- UPDATE Library SET Address = 'Strada 126' WHERE ID = 20
-- SELECT * FROM Library

